export enum QueryKeys {
  GET_USD_VALUE = "TWAP_GET_USD_VALUE",
  GET_BALANCE = "TWAP_GET_BALANCE",
  GET_ORDER_HISTORY = "TWAP_GET_ORDER_HISTORY",
  GET_ALLOWANCE = "TWAP_GET_ALLOWANCE",
  GET_GAS_PRICE = "TWAP_GET_GAS_PRICE",
}
